# -*- coding: utf-8 -*-
"""acquisition

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14_i_xWQx9reHGCSgAMQHVNB5HkXY_LZ2
"""

!mkdir -p data/raw

import requests
import hashlib

usda_url = "https://ers.usda.gov/sites/default/files/_laserfiche/DataFiles/113063/2025-food-environment-atlas-data.zip"
usda_filename = "data/raw/usda_food_atlas_2025.zip"

response_usda = requests.get(usda_url)
with open(usda_filename, "wb") as f:
    f.write(response_usda.content)
print("Saved USDA dataset.")

cdc_url = "https://uofi.box.com/shared/static/kyr7iscrhy6943ictwt7voadier5mf7s"
cdc_filename = "data/raw/cdc_places_2024.csv"

response_cdc = requests.get(cdc_url)
with open(cdc_filename, "wb") as f:
    f.write(response_cdc.content)
print("Saved CDC dataset.")

def sha256_checksum(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()

print("\nSHA-256 Checksums:")
print("USDA:", sha256_checksum(usda_filename))
print("CDC :", sha256_checksum(cdc_filename))
