# -*- coding: utf-8 -*-
"""acquire_cdc

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P_iNeWzUsFNmCfe9D1nH297YVQI4k85A
"""

import os
import requests
import hashlib

"""# CDC dataset URL and output name

"""

os.makedirs("data/raw", exist_ok=True)

cdc_url = "https://uofi.box.com/shared/static/kyr7iscrhy6943ictwt7voadier5mf7s"
cdc_filename = "data/raw/cdc_places_2024.csv"

"""# Download CDC dataset

"""

response = requests.get(cdc_url)
with open(cdc_filename, "wb") as f:
    f.write(response.content)

print("Saved CDC dataset:", cdc_filename)

"""# Compute SHA-256

"""

def sha256(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()

print("CDC SHA-256:", sha256(cdc_filename))