# -*- coding: utf-8 -*-
"""acquire_usda

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1humZh_HOMo_NyhHf_Tu-DfjHKjje0h_9
"""

import os
import requests
import hashlib

"""# USDA dataset URL and output name"""

os.makedirs("data/raw", exist_ok=True)

usda_url = "https://ers.usda.gov/sites/default/files/_laserfiche/DataFiles/113063/2025-food-environment-atlas-data.zip"
usda_filename = "data/raw/usda_food_atlas_2025.zip"

"""# Download USDA dataset"""

response = requests.get(usda_url)

with open(usda_filename, "wb") as f:
    f.write(response.content)

print("Saved USDA dataset:", usda_filename)

"""# Compute SHA-256"""

def sha256(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()

print("USDA SHA-256:", sha256(usda_filename))

