# -*- coding: utf-8 -*-
"""analysis-IS 477

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ppT-aDA5SZE2QJsYtmaAd-DZVlLfBYdl
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv("data/processed/merged_output_cleaned.csv")

correlation = df["fast_food_density"].corr(df["Obesity_Rate"])

print("Correlation between fast food density and obesity rate:")
print(correlation)

plt.figure(figsize=(7,5))
plt.scatter(df["fast_food_density"], df["Obesity_Rate"], alpha=0.5)
plt.xlabel("Fast Food Restaurant Density")
plt.ylabel("Obesity Rate (%)")
plt.title("Obesity Rate vs Fast Food Density")

plt.savefig("obesity_fastfood_scatter.png", dpi=300)
plt.show()

x = df["fast_food_density"]
y = df["Obesity_Rate"]

m, b = np.polyfit(x, y, 1)

plt.figure(figsize=(7,5))
plt.scatter(x, y, alpha=0.5)
plt.plot(x, m*x + b, color='red')

plt.xlabel("Fast Food Density")
plt.ylabel("Obesity Rate (%)")
plt.title("Obesity Rate vs Fast Food Density")

plt.savefig("obesity_fastfood_regression.png", dpi=300)
plt.show()
