# -*- coding: utf-8 -*-
"""integration

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q7iZIj64yvVd7C1Zy0HHJbkCxLenJ14T
"""

import pandas as pd
import os

"""# Make sure "Merge" folder exists

"""

os.makedirs("data/merge", exist_ok=True)

"""# Load cleaned datasets"""

cdc = pd.read_csv("data/clean_1/cdc_cleaned.csv")
atlas = pd.read_csv("data/clean_1/foodatlas_clean.csv")

"""# Merge on FIPS"""

merged = pd.merge(cdc, atlas, on="FIPS", how="inner")

"""# Save merged dataset"""

merged.to_csv("data/merge/merged_output.csv", index=False)

print("Merged dataset saved to data/merge/merged_output.csv")