# -*- coding: utf-8 -*-
"""integration - IS 477

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V4p4z2UlkiLwoCV-ofjCko8ez2MyTqay
"""

import pandas as pd

cdc = pd.read_csv('/content/cdc_cleaned.csv')
atlas = pd.read_csv('/content/foodatlas-cleaned.csv')

merged = pd.merge(cdc, atlas, on='FIPS', how='inner')

merged.head()
merged.to_csv('merged_output.csv', index=False)